import string

def make_rot_n(n):
 lc = string.ascii_lowercase
 uc = string.ascii_uppercase
 trans = string.maketrans(lc + uc,
                          lc[n:] + lc[:n] + uc[n:] + uc[:n])
 return lambda s: string.translate(s, trans)

rot1 = make_rot_n(1)
rot2 = make_rot_n(2)
rot3 = make_rot_n(3)
rot4 = make_rot_n(4)
rot5 = make_rot_n(5)
rot6 = make_rot_n(6)
rot7 = make_rot_n(7)
rot8 = make_rot_n(8)
rot9 = make_rot_n(9)
rot10 = make_rot_n(10)
rot11 = make_rot_n(11)
rot12 = make_rot_n(12)
rot13 = make_rot_n(13)
rot14 = make_rot_n(14)
rot15 = make_rot_n(15)
rot16 = make_rot_n(16)
rot17 = make_rot_n(17)
rot18 = make_rot_n(18)
rot19 = make_rot_n(19)
rot20 = make_rot_n(20)
rot21 = make_rot_n(21)
rot22 = make_rot_n(22)
rot23 = make_rot_n(23)
rot24 = make_rot_n(24)
rot25 = make_rot_n(25)

phrase = raw_input("Enter Encrypted ROT Phrase: ")

print rot1(phrase)
print rot2(phrase)
print rot3(phrase)
print rot4(phrase)
print rot5(phrase)
print rot6(phrase)
print rot7(phrase)
print rot8(phrase)
print rot9(phrase)
print rot10(phrase)
print rot11(phrase)
print rot12(phrase)
print rot13(phrase)
print rot14(phrase)
print rot15(phrase)
print rot16(phrase)
print rot17(phrase)
print rot18(phrase)
print rot19(phrase)
print rot20(phrase)
print rot21(phrase)
print rot22(phrase)
print rot23(phrase)
print rot24(phrase)
print rot25(phrase)

raw_input("Press Enter Key to Exit")
